baseURL = "https://lindsay-kislingbury.github.io/"
languageCode = "en-us"
title = "Lindsay Kislingbury's Portfolio"

[build]
writeStats = true

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"
